# This is a workflow to automate the dataset creation of wastewater data for Ottawa.

name: Ottawa-Dataset-creation

# Runs everyday at 2:15pm EST/EDT (19:15 UTC)
on:
  schedule:
    - cron: '15 19 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  dataset-creation:
    runs-on: "macOS-latest"
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      - name: Download Ottawa wastewater data
        run: |
            curl -H "Authorization: token ${{ secrets.PAT_TOKEN }}" -H "Accept: application/vnd.github.v4.raw" -L https://api.github.com/repos/Big-Life-Lab/PHESD-private/contents/Ottawa/Data/wastewater_virus.csv --output "Wastewater/Ottawa/Data/wastewater_virus.csv" --create-dirs -L https://api.github.com/repos/Big-Life-Lab/PHESD-private/contents/Ottawa/Data/wwMeasure.csv --output "Wastewater/Ottawa/Data/wwMeasure.csv" --create-dirs
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Update Ottawa data" -a || echo "Nothing to update"
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACTION_TOKEN }}
          branch: 'main'
